### PR TITLE
Fixed discord invite link regex (#107)

### LINKED ISSUE #4: Discord Liks are not detected
**Describe the bug**
Discord Liks are not detected

**To Reproduce**
Post:
```
```html
<a href="https://discord.gg/Y25s2URa">Discord</a>
\```
```
(Without the `\`)

**Expected behavior**
DELETE THE MESSAGE!

**Screenshots**
grafik

**Your Configuration (please complete the following information):**
Ask Discord user with the ID "251344185783746560"

**Additional context**
Add a basic discord invite Link regex

### LINKED ISSUE #107: Discord Liks are not detected
**Describe the bug**
Discord Liks are not detected

**To Reproduce**
Post:
```
```html
<a href="https://discord.gg/Y25s2URa">Discord</a>
\```
```
(Without the `\`)

**Expected behavior**
DELETE THE MESSAGE!

**Screenshots**
grafik

**Your Configuration (please complete the following information):**
Ask Discord user with the ID "251344185783746560"

**Additional context**
Add a basic discord invite Link regex

### PR DESCRIPTION
**Pull request by MarcelCoding**
**Description**
Fixed discord invite link regex (#107)

**Issue**
Closes #107

### CODE REVIEW

**Review by JannikEmmerich — APPROVED** [review]

**Review by florian-sabonchi — COMMENTED** [review]
Shouldn't the .gitignore rather be included in a separate commit?

**Review by ghost — APPROVED** [review]

**Comment by MarcelCoding** [comment]
> Shouldn't the .gitignore rather be included in a separate commit?

@FlorianJSa this pull request will be squashed, so there is no need to put the changes in different  commits.

**Comment by MarcelCoding** [comment]
@Defelo Nico told me that you said, there are some cases that links are not been recognized. Can you please send me an example, that I can integrate these cases into the regex.

**Comment by MarcelCoding** [comment]
Ok, except for one all invites are detected. Due to the fact that this link (`https://discord.gg/ JTYzZ9`) contains a space, we would have to disable links that contain the word `discord`, which I wouldn't recommend. Because you may want to link discord messaged or media files.

**Pull request closed without merging**
